name: Build and Run Project

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      TENCENT_CLOUD_SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
      TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
      TOKEN: ${{ secrets.TOKEN }}
      NAME: ${{ secrets.NAME }}
      REPOSITORY: ${{ secrets.REPOSITORY }}
      COSURL: ${{ secrets.COSURL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Show Go env
        run: go env

      - name: Go mod tidy
        run: go mod tidy

      - name: Build and run
        run: go run ./cmd/main.go

      - name: Run the app
        run: |
          chmod +x lhasaRSS
          ./lhasaRSS