name: RSS Scheduler

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      TENCENT_CLOUD_SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
      TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
      TOKEN: ${{ secrets.TOKEN }}
      NAME: ${{ secrets.NAME }}
      REPOSITORY: ${{ secrets.REPOSITORY }}
      COSURL: ${{ secrets.COSURL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: |
          cd api/lhasaRSS
          go mod download

      - name: Build
        run: |
          cd api/lhasaRSS
          go build -o myapp ./cmd/main.go

      - name: Run the app
        run: |
          cd api/lhasaRSS
          chmod +x myapp
          ./myapp

      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-logs
          path: api/lhasaRSS/logs
