name: ScheduledRssRawler

on:
  schedule:
    # 每小时执行一次
    - cron: '0 * * * *'
  # 支持手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./api

    - name: Build
      run: go build -o main
      working-directory: ./api

    - name: Run Go program
      run: ./main
      working-directory: ./api

    - name: Check for generated file
      run: |
        if [ -f "./api/data/filename.json" ]; then
          echo "Generated file exists."
          cat ./api/data/filename.json
        else
          echo "Generated file not found."
        fi
