name: ScheduledRssRawler

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次（UTC时间）
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      WORKDIR: ./api/GrabLatestRSS  # 关键路径定义

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify go.sum Location  # 新增路径验证
      run: |
        echo "Current directory: $(pwd)"
        ls -la ${{ env.WORKDIR }}
        [ -f ${{ env.WORKDIR }}/go.sum ] || (echo "go.sum not found"; exit 1)

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'
        cache: true
        cache-dependency-path: ${{ env.WORKDIR }}/go.sum  # 精确指向目标文件

    - name: Install dependencies
      working-directory: ${{ env.WORKDIR }}
      run: |
        go mod tidy -v
        go mod download

    - name: Build
      working-directory: ${{ env.WORKDIR }}
      env:
        CGO_ENABLED: 0
      run: |
        go build -v -ldflags="-s -w" -o rss-crawler

    - name: Run Crawler
      working-directory: ${{ env.WORKDIR }}
      env:
        TOKEN: ${{ secrets.TOKEN }}
        NAME: ${{ secrets.NAME }}
        REPOSITORY: ${{ secrets.REPOSITORY }}
      run: |
        ./rss-crawler